### ISSUE TITLE
Endless loop on launch

### ISSUE THREAD

**Issue by Graphicscore** [200Tigersbloxed/HRtoVRChat_OSC#9]
I can't launch the Application anymore, it worked fine with this config before.
Now I am stuck in an endless loop:

`[14:24:13] [HRtoVRChat_OSC.Program] (WARN): HRListener is currently inactive! Start it first!
[14:24:13] [HRtoVRChat_OSC.HRManagers.PulsoidManager] (LOG): Initialized WebSocket!
[14:24:13] [HRtoVRChat_OSC.WebsocketTemplate+<Start>d__5:Void MoveNext()] (ERROR): Failed to connect to WebSocket server! Exception:  | Exception: System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '521' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at HRtoVRChat_OSC.WebsocketTemplate.Start() in E:\RiderProjects\HRtoVRChat_OSC\HRtoVRChat_OSC\WebsocketTemplate.cs:line 25
[14:24:13] [HRtoVRChat_OSC.Program] (WARN): HRListener is currently inactive! Start it first!
[14:24:13] [HRtoVRChat_OSC.HRManagers.PulsoidManager] (LOG): Initialized WebSocket!
[14:24:13] [HRtoVRChat_OSC.Program] (WARN): HRListener is currently inactive! Start it first!`

**Comment by 200Tigersbloxed** [comment]
This was an issue with the backend on the HRProxy server. It has been fixed and rebooted and you should not see this issue anymore. Sorry for the inconvenience!
